/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codebind;

/**
 *
 * @author Darcy
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jradiobutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbutton = new javax.swing.JButton();
        jcheckbox = new javax.swing.JButton();
        jlabel = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 136, 123));
        jPanel1.setEnabled(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 474));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 474));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, -1));

        jradiobutton.setBackground(new java.awt.Color(231, 220, 201));
        jradiobutton.setText("JRADIOBUTTON");
        jradiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobuttonActionPerformed(evt);
            }
        });
        jPanel1.add(jradiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 120, 60));

        jButton2.setBackground(new java.awt.Color(231, 220, 201));
        jButton2.setText("JTEXTAREA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, 60));

        jbutton.setBackground(new java.awt.Color(231, 220, 201));
        jbutton.setText("JBUTTON");
        jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 110, 60));

        jcheckbox.setBackground(new java.awt.Color(231, 220, 201));
        jcheckbox.setText("JCHECKBOX");
        jcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckboxActionPerformed(evt);
            }
        });
        jPanel1.add(jcheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 110, 60));

        jlabel.setBackground(new java.awt.Color(231, 220, 201));
        jlabel.setText("JLABEL");
        jlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabelActionPerformed(evt);
            }
        });
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 60));

        jButton6.setBackground(new java.awt.Color(231, 220, 201));
        jButton6.setText(" JTOGGLEBUTTON");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 140, 60));

        jButton7.setBackground(new java.awt.Color(231, 220, 201));
        jButton7.setText("JMENUBAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 110, 60));

        jButton8.setBackground(new java.awt.Color(231, 220, 201));
        jButton8.setText("JTEXTFIELD");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 120, 60));

        jButton9.setBackground(new java.awt.Color(231, 220, 201));
        jButton9.setText(" JCOMBOBOX");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 60));

        jButton10.setBackground(new java.awt.Color(231, 220, 201));
        jButton10.setText(" JTABLE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 110, 60));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(114, 41, 41));
        jLabel2.setText("Tutorial de java");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 370, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyTextArea_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabelActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyLabel_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jlabelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyToggleButton_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMenubar_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyTextField_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCombobox_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyTable_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyButton_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jbuttonActionPerformed

    private void jradiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobuttonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyRadioButton_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jradiobuttonActionPerformed

    private void jcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckboxActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCheckBox().setVisible(true);
            }
        });
    }//GEN-LAST:event_jcheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton;
    private javax.swing.JButton jcheckbox;
    private javax.swing.JButton jlabel;
    private javax.swing.JButton jradiobutton;
    // End of variables declaration//GEN-END:variables
}
