/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codebind;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Darcy
 */
public class MyButton_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MyButton_GUI
     */
    public MyButton_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabel = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbuttongris = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbuttonrosa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(200, 174, 128));
        bg.setMinimumSize(new java.awt.Dimension(600, 474));
        bg.setPreferredSize(new java.awt.Dimension(600, 474));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(114, 41, 41));
        jLabel2.setText("JBUTTON");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 230, 60));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel1.setText("Descripción  ");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 150, 60));

        jlabel.setEditable(false);
        jlabel.setBackground(new java.awt.Color(200, 174, 128));
        jlabel.setColumns(20);
        jlabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jlabel.setRows(5);
        jlabel.setText("\n\n      \n      La clase JButton proporciona un botón visible\n      que los desarrolladores pueden añadir a cualquier\n      interfaz de usuario en Java, ajustando su apariencia \n      y comportamiento para adaptarla a las necesidades \n      de un proyecto. ");
        jlabel.setAutoscrolls(false);
        jlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 174, 128)));
        jlabel.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        bg.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 130));

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel3.setText("Ejercicio:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 60));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("De clic sobre uno de los  botones para cambiar el fondo de pantalla ");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 30));

        jbuttongris.setBackground(new java.awt.Color(153, 153, 153));
        jbuttongris.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jbuttongris.setText("Fondo gris");
        jbuttongris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttongrisActionPerformed(evt);
            }
        });
        bg.add(jbuttongris, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 140, 50));

        jButton2.setBackground(new java.awt.Color(127, 60, 60));
        jButton2.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButton2.setText("Ir al inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bg.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 130, 40));

        jbuttonrosa.setBackground(new java.awt.Color(255, 204, 204));
        jbuttonrosa.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jbuttonrosa.setText("Fondo rosa");
        jbuttonrosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonrosaActionPerformed(evt);
            }
        });
        bg.add(jbuttonrosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 140, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/jbutton.png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttongrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttongrisActionPerformed
        bg.setBackground(Color.LIGHT_GRAY);
        jlabel.setBackground(Color.LIGHT_GRAY);
        jlabel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
      
    }//GEN-LAST:event_jbuttongrisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbuttonrosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonrosaActionPerformed
        bg.setBackground(Color.PINK);
        jlabel.setBackground(Color.pink);
        jlabel.setBorder(BorderFactory.createLineBorder(Color.pink));
            
        
    }//GEN-LAST:event_jbuttonrosaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyButton_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbuttongris;
    private javax.swing.JButton jbuttonrosa;
    private javax.swing.JTextArea jlabel;
    // End of variables declaration//GEN-END:variables
}
