/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codebind;

/**
 *
 * @author Darcy
 */
public class MyCombobox_GUI extends javax.swing.JFrame {

    /**
     * Creates new form My_Combobox_GUI
     */
    public MyCombobox_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        grados = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg1.setBackground(new java.awt.Color(200, 174, 128));
        bg1.setInheritsPopupMenu(true);
        bg1.setMinimumSize(new java.awt.Dimension(600, 474));
        bg1.setPreferredSize(new java.awt.Dimension(600, 474));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 41, 41));
        jLabel4.setText("JCOMBOBOX");
        bg1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 270, 60));

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel5.setText("Descripción  ");
        bg1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, 60));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(200, 174, 128));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n      \n      \n       La clase JComboBox presenta una caja de \n       combinación (combobox) Esta clase es similar \n       a la clase JRadioButton en que también permite  \n       al usuario seleccionar un ítem de una lista de po-\n       sibles opciones\n");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 174, 128)));
        jTextArea2.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        bg1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 140));

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel6.setText("Ejercicio:");
        bg1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 60));

        resultado.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        resultado.setText("   Tu grado es:");
        resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        bg1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 220, 40));

        jButton3.setBackground(new java.awt.Color(127, 60, 60));
        jButton3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButton3.setText("Ir al inicio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bg1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 130, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/seleccion.jpg"))); // NOI18N
        bg1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        grados.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        grados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Septimo", "Octavo", "Noveno", "Decimo" }));
        grados.setName(""); // NOI18N
        grados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradosActionPerformed(evt);
            }
        });
        bg1.add(grados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 200, 40));

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel9.setText("Elija el grado al que pertenece");
        bg1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradosActionPerformed
        String texto="   Tu grado es: ";
        texto=texto+grados.getSelectedItem().toString();
        resultado.setText(texto);
    }//GEN-LAST:event_gradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCombobox_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCombobox_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCombobox_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCombobox_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCombobox_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg1;
    private javax.swing.JComboBox<String> grados;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
