/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codebind;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Darcy
 */
public class MyMenubar_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MyMenubar_GUI
     */
    public MyMenubar_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jlabel = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        morado = new javax.swing.JMenuItem();
        azul = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(200, 174, 128));
        bg.setInheritsPopupMenu(true);
        bg.setMinimumSize(new java.awt.Dimension(600, 474));
        bg.setPreferredSize(new java.awt.Dimension(600, 474));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 41, 41));
        jLabel4.setText("JMENUBAR");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, 60));

        titulo.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        titulo.setText("Descripción  ");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 60));

        jlabel.setEditable(false);
        jlabel.setBackground(new java.awt.Color(200, 174, 128));
        jlabel.setColumns(20);
        jlabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jlabel.setRows(5);
        jlabel.setText("En la parte superior de esta pantalla se puede observar \nun menú bar en el que podemos cambiar el color de \nfondo del panel principal.");
        jlabel.setAutoscrolls(false);
        jlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 174, 128)));
        jlabel.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        bg.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 380, 60));

        jButton3.setBackground(new java.awt.Color(127, 60, 60));
        jButton3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButton3.setText("Ir al inicio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bg.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 130, 40));

        titulo1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        titulo1.setText("Ejercicio:");
        bg.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, 60));

        jlabel1.setEditable(false);
        jlabel1.setBackground(new java.awt.Color(200, 174, 128));
        jlabel1.setColumns(20);
        jlabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jlabel1.setRows(5);
        jlabel1.setText("\n\n      \n      \n       Es la barra de menú principal. Una barra\n       horizontal alargada en la que se colocarán \n       las distintas opciones. Si miras en tu nave- \n       gador, arriba, verás una barra de estas con \n       opciones como \"Archivo\", \"Editar\", etc.\n");
        jlabel1.setAutoscrolls(false);
        jlabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 174, 128)));
        jlabel1.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        bg.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 340, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/main.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jMenu2.setText("Opciones");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu3.setText("Fondo de pantalla");

        morado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        morado.setText("Morado");
        morado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moradoActionPerformed(evt);
            }
        });
        jMenu3.add(morado);

        azul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        azul.setText("Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        jMenu3.add(azul);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        
        if (evt.getSource()==azul) {
            bg.setBackground(new Color(176, 196, 222));
            jlabel.setBackground(new Color(176, 196, 222));
            titulo.setBackground(new Color(176, 196, 222));
            jlabel.setBorder(BorderFactory.createLineBorder(new Color(176, 196, 222)));
            jlabel1.setBackground(new Color(176, 196, 222));
            titulo1.setBackground(new Color(176, 196, 222));
            jlabel1.setBorder(BorderFactory.createLineBorder(new Color(176, 196, 222)));
            
        }
        
    }//GEN-LAST:event_azulActionPerformed

    private void moradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moradoActionPerformed
           if (evt.getSource()==morado) {
            bg.setBackground(new Color(216, 191, 216));
            jlabel.setBackground(new Color(216, 191, 216));
            titulo.setBackground(new Color(216, 191, 216));
            jlabel.setBorder(BorderFactory.createLineBorder(new Color(216, 191, 216)));
            jlabel1.setBackground(new Color(216, 191, 216));
            titulo1.setBackground(new Color(216, 191, 216));
            jlabel1.setBorder(BorderFactory.createLineBorder(new Color(216, 191, 216)));
            
        }
    }//GEN-LAST:event_moradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMenubar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMenubar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMenubar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMenubar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMenubar_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem azul;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextArea jlabel;
    private javax.swing.JTextArea jlabel1;
    private javax.swing.JMenuItem morado;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
