/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codebind;

/**
 *
 * @author Darcy
 */
public class MyRadioButton_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MyRadioButton_GUI
     */
    public MyRadioButton_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tamaño = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        jbutton = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(200, 174, 128));
        bg.setMinimumSize(new java.awt.Dimension(600, 474));
        bg.setPreferredSize(new java.awt.Dimension(600, 474));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(114, 41, 41));
        jLabel2.setText("JRADIOBUTTON");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 340, 60));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel1.setText("Descripción  ");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, 60));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(200, 174, 128));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\n      \n      Conocido también como botón de opción o\n      botón de radio es un tipo de widget utilizado \n      en interfaces gráficas de usuario que permite \n      elegir una sola opción de un conjunto predeter-\n      minado de estas. ");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 174, 128)));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        bg.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 130));

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel3.setText("Ejercicio:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, 60));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("De clic sobre una de las opciones");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, 30));

        jButton2.setBackground(new java.awt.Color(127, 60, 60));
        jButton2.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButton2.setText("Ir al inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bg.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/radiobutton.png"))); // NOI18N
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(200, 174, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elegir el tamaños del panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Britannic Bold", 0, 18))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(213, 120));

        tamaño.add(radio1);
        radio1.setText("25* 25");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        tamaño.add(radio2);
        radio2.setText("30*45");

        tamaño.add(radio3);
        radio3.setText("50*65");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio1)
                .addGap(10, 10, 10)
                .addComponent(radio2)
                .addGap(10, 10, 10)
                .addComponent(radio3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1)
                    .addComponent(radio2)
                    .addComponent(radio3))
                .addGap(30, 30, 30))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 240, 120));

        jbutton.setBackground(new java.awt.Color(127, 60, 60));
        jbutton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jbutton.setText("Realizar cambio");
        jbutton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jbuttonStateChanged(evt);
            }
        });
        jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActionPerformed(evt);
            }
        });
        bg.add(jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 140, 40));

        panel.setBackground(new java.awt.Color(133, 124, 141));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bg.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActionPerformed
      if (radio1.isSelected()) {
			panel.setSize(25,25);
		}
		if (radio2.isSelected()) {
			panel.setSize(30,45);
		}
		if (radio3.isSelected()) {
			panel.setSize(50,65);
		} 

    }//GEN-LAST:event_jbuttonActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1ActionPerformed

   
    private void jbuttonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jbuttonStateChanged
        
    }//GEN-LAST:event_jbuttonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyRadioButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyRadioButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyRadioButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyRadioButton_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyRadioButton_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbutton;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    public static javax.swing.ButtonGroup tamaño;
    // End of variables declaration//GEN-END:variables
}
